version: "3.9"
x-clickhouse-credentials: &clickhouse-credentials
  CLICKHOUSE_USER: dittofeed
  CLICKHOUSE_PASSWORD: password
x-backend-app-env: &backend-app-env
  <<: *clickhouse-credentials
  NODE_ENV: production
  DATABASE_HOST: ${DATABASE_HOST:-postgres}
  DATABASE_PORT: ${DATABASE_PORT:-5432}
  DATABASE_USER: ${DATABASE_USER:-postgres}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
  CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-http://clickhouse-server:8123}
  TEMPORAL_ADDRESS: ${TEMPORAL_ADDRESS:-temporal:7233}
  WORKSPACE_NAME: ${WORKSPACE_NAME:-Default}
  AUTH_MODE: ${AUTH_MODE:-multi-tenant}
  SECRET_KEY: ${SECRET_KEY:-GEGL1RHjFVOxIO80Dp8+ODlZPOjm2IDBJB/UunHlf3c=}
  DASHBOARD_API_BASE: ${DASHBOARD_API_BASE:-http://localhost:3000}
  ONBOARDING_URL: "/dashboard-l/onboarding"
  SIGNOUT_URL: "/dashboard/signout"
services:
  ee:
    image: dittofeed/dittofeed-ee:v0.22.0-ee.6
    command: node --max-old-space-size=${MEM_LIMIT:-824} ./packages/ee/dist/scripts/startLite.js
    deploy:
      resources:
        limits:
          memory: ${CONTAINER_MEM_LIMIT:-1024}m
    ports:
      - "3000:3000"
    logging:
      driver: "local"
    depends_on:
      - postgres
      - temporal
      - clickhouse-server
    env_file:
      - .env
    environment:
      <<: *backend-app-env
      DASHBOARD_API_BASE: "http://localhost:3000"
      # comment out after initial setup
      BOOTSTRAP: "true"
      PORT: "3000"
      HOST: "0.0.0.0"
    # README: To add local env variables uncomment the following line and add a .env file in the root directory
    # env_file:
    #   - .env
    networks:
      - dittofeed-network-ee
  postgres:
    image: "postgres:15"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dittofeed
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    logging:
      driver: "local"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dittofeed-network-ee
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.12.6.70-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    logging:
      driver: "local"
    deploy:
      resources:
        limits:
          memory: ${CLICKHOUSE_CONTAINER_MEM_LIMIT:-2048}m
    environment:
      <<: *clickhouse-credentials
    volumes:
      - ./packages/backend-lib/clickhouse_config.dev.xml:/etc/clickhouse-server/config.xml
      - clickhouse_lib:/var/lib/clickhouse
      - clickhouse_log:/var/log/clickhouse-server
    networks:
      - dittofeed-network-ee
  admin-cli:
    image: dittofeed/dittofeed-admin-cli-licensed:v0.22.0-ee.6
    entrypoint: []
    profiles: ["admin-cli"]
    command: tail -f /dev/null
    tty: true
    logging:
      driver: "local"
    depends_on:
      - postgres
      - temporal
      - clickhouse-server
    environment:
      <<: *backend-app-env
    # README: To add local env variables uncomment the following line and add a .env file in the root directory
    # env_file:
    #   - .env
    networks:
      - dittofeed-network-ee
  temporal:
    depends_on:
      - postgres
    environment:
      - DB=postgresql
      - DB_PORT=${DATABASE_PORT:-5432}
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PWD=${DATABASE_PASSWORD:-password}
      - POSTGRES_SEEDS=${DATABASE_HOST:-postgres}
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/prod.yaml
    # README: To add local env variables uncomment the following line and add a .env file in the root directory
    # env_file:
    #   - .env
    image: temporalio/auto-setup:${TEMPORAL_VERSION:-1.22.4}
    labels:
      kompose.volume.type: configMap
    networks:
      - dittofeed-network-ee
    ports:
      - 7233:7233
    logging:
      driver: "local"
    volumes:
      - ./packages/backend-lib/temporal-dynamicconfig:/etc/temporal/config/dynamicconfig
volumes:
  postgres:
  clickhouse_lib:
  clickhouse_log:

networks:
  dittofeed-network-ee:
    driver: bridge
    name: dittofeed-network-ee
